apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-example
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
    env: prod
  ports:
    - nodePort: 32410
      protocol: TCP
      port: 80
      targetPort: 80
