apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
# CAN ADD MANY DIFFERENT TYPES HERE. OPAQUE is default. All values must be Base64.
# NOTE - NOT SECURE AS BASE64 STRINGS ARE NOT ENCRYPTED.
# Typically can pull from a cloud provider Key store here instead.
# Can protect Secrets using Role Based Access Control Policies (RBAC)
# Or can store secrets with Cloud Providers like Azure Key Vault
# and AWS Key Management Service
type: Opaque
data:
  username: VGhlVXNlck5hbWU=
  password: bXlwYXNzd29yZA==
