apiVersion: v1
kind: Pod
metadata:
  name: mybox-volume-pvc-ex
spec:
  restartPolicy: Always
  containers:
    - name: mybox-container-volume-pvc
      image: busybox
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      command:
        - sleep
        - "3600"
      volumeMounts:
        # Will create a "demo" folder inside Busy Box Container
        - mountPath: "/demo/"
          name: my-pod-volume
  volumes:
    - name: my-pod-volume
      persistentVolumeClaim:
        claimName: persistent-volume-claim-ex
