apiVersion: v1
kind: Service
metadata:
  # Note, this is the domain name we will use in busy box to get the NGINX homepage.
  # Will run command "wget -qO- http://svc-clusterip-example:8080"
  name: svc-clusterip-example
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: app-clusterip-example
    env: prod
