apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-example
spec:
  containers:
    - name: liveness
      image: busybox
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      args:
        - sh
        - -c
        # Will fail here. We are removing all files due to "rm -rf /tmp/healthy" so cat will return "No such file or directory"
        - touch /tmp/healthy; sleep 15; rm -rf /tmp/healthy; sleep 3600

      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 2
