apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer-example
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
